"""create fuel_records table

Revision ID: 0d5d2a9f7ef0
Revises: 
Create Date: 2025-12-11 15:45:38.918173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d5d2a9f7ef0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_identifier', sa.String(length=20), nullable=False),
    sa.Column('station_name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('collection_datetime', sa.DateTime(), nullable=False),
    sa.Column('fuel_type', sa.String(length=50), nullable=False),
    sa.Column('sale_price', sa.Float(), nullable=False),
    sa.Column('sold_volume', sa.Float(), nullable=False),
    sa.Column('driver_name', sa.String(length=200), nullable=False),
    sa.Column('driver_cpf', sa.String(length=14), nullable=False),
    sa.Column('vehicle_plate', sa.String(length=8), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_records_city'), 'fuel_records', ['city'], unique=False)
    op.create_index(op.f('ix_fuel_records_collection_datetime'), 'fuel_records', ['collection_datetime'], unique=False)
    op.create_index(op.f('ix_fuel_records_driver_cpf'), 'fuel_records', ['driver_cpf'], unique=False)
    op.create_index(op.f('ix_fuel_records_fuel_type'), 'fuel_records', ['fuel_type'], unique=False)
    op.create_index(op.f('ix_fuel_records_id'), 'fuel_records', ['id'], unique=False)
    op.create_index(op.f('ix_fuel_records_state'), 'fuel_records', ['state'], unique=False)
    op.create_index(op.f('ix_fuel_records_station_identifier'), 'fuel_records', ['station_identifier'], unique=False)
    op.create_index(op.f('ix_fuel_records_vehicle_type'), 'fuel_records', ['vehicle_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fuel_records_vehicle_type'), table_name='fuel_records')
    op.drop_index(op.f('ix_fuel_records_station_identifier'), table_name='fuel_records')
    op.drop_index(op.f('ix_fuel_records_state'), table_name='fuel_records')
    op.drop_index(op.f('ix_fuel_records_id'), table_name='fuel_records')
    op.drop_index(op.f('ix_fuel_records_fuel_type'), table_name='fuel_records')
    op.drop_index(op.f('ix_fuel_records_driver_cpf'), table_name='fuel_records')
    op.drop_index(op.f('ix_fuel_records_collection_datetime'), table_name='fuel_records')
    op.drop_index(op.f('ix_fuel_records_city'), table_name='fuel_records')
    op.drop_table('fuel_records')
    # ### end Alembic commands ###
